name     = "thor"
version  = "0.5.0"
out      = "build/"
entry    = "src/main.zp"
compiler = "tools/zapc-no-pie"
flags    = "-Lvendor/zap-toml/lib -lztoml"

[imports]
"@zap-requests" = "./vendor/zap-requests/src"
"@toml" = "./vendor/zap-toml/src"


[dependencies]
"zap-requests" = { url = "https://github.com/zap-tooling/zap-requests", version = "b3e368a79f6463594b6c06d3bbc926b8c7ed8388", commit = "b3e368a79f6463594b6c06d3bbc926b8c7ed8388" }
"zap-toml" = { url = "https://github.com/thezaplang/zap-toml", version = "1053f4d97eff68e45a0027b36b29bd69eaa6ddb1", commit = "1053f4d97eff68e45a0027b36b29bd69eaa6ddb1" }
